"""Stable agent-facing API surface for HDA.

Import from ``hda.tools`` or ``hda.tools.agent_tools`` when building agents on
top of the project. Internal modules under ``hda.analysis``, ``hda.db``, and
``hda.api`` may evolve faster.
"""

from hda.tools.agent_tools import (
    append_context_entry,
    archive_context_block,
    annotate,
    annotate_my_snp,
    available_panels,
    compare,
    compare_panel,
    compare_variant,
    estimate_relatedness,
    export_doctor_report,
    get_stats,
    import_context_inbox,
    import_context_document,
    list_context_inbox,
    list_context_documents,
    list_context_sections,
    list_all_subjects,
    lookup_snp,
    migrate_context,
    move_context_block,
    notable_findings,
    read_context_audit,
    read_context_block,
    replace_context_entry,
    replace_context_section,
    read_context,
    run_all_panels,
    run_panel,
    search,
    upsert_context_block,
    validate_context,
    write_context_document,
    who_am_i,
)

__all__ = [
    "append_context_entry",
    "archive_context_block",
    "annotate",
    "annotate_my_snp",
    "available_panels",
    "compare",
    "compare_panel",
    "compare_variant",
    "estimate_relatedness",
    "export_doctor_report",
    "get_stats",
    "import_context_inbox",
    "import_context_document",
    "list_context_inbox",
    "list_context_documents",
    "list_context_sections",
    "list_all_subjects",
    "lookup_snp",
    "migrate_context",
    "move_context_block",
    "notable_findings",
    "read_context_audit",
    "read_context_block",
    "replace_context_entry",
    "replace_context_section",
    "read_context",
    "run_all_panels",
    "run_panel",
    "search",
    "upsert_context_block",
    "validate_context",
    "write_context_document",
    "who_am_i",
]
